version: "3.8"
services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    environment:
      POSTGRES_USER: "datadigital"
      POSTGRES_PASSWORD: "datad1g1tal"
      POSTGRES_DB: "dwh"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

networks:
  default:
    name: data_network
