---
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama/data:/root/.ollama
    ports:
      - "11434:11434"

networks:
  default:
    name: data_network
